# Generated by Django 2.1.7 on 2019-03-22 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'URL Address',
                'verbose_name_plural': 'URL Addresses',
                'ordering': ('url',),
            },
        ),
    ]
