# Generated by Django 2.2 on 2019-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_urlperm_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlperm',
            name='expire',
        ),
        migrations.AddField(
            model_name='urlperm',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urlperm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
