# Generated by Django 2.2 on 2019-04-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_auto_20190420_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.Address'),
        ),
    ]
