# Generated by Django 2.2 on 2019-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('in_progress', 'in progress')], default='in_progress', max_length=20),
        ),
    ]
